### ISSUE TITLE
final aim of hemlock

### ISSUE THREAD

**Issue by aosama** [Lab41/Hemlock#3]
hi, 

is the final aim of hemlock is to deal with existing relational databases as if they were a graph db, hence working with the data in terms of nodes and edges?

**Comment by cglewis** [comment]
@aosama no, Hemlock is not aimed at graph databases specifically.  It is aimed more to be modular for adding whatever database, filesystem, or other storage system, and putting that into a standard format (in this case JSON), and making the data from all of those different systems and different formats available on a distributed schema free document-oriented system (couchbase and elasticsearch) so that it can be queried in a consistent standard way.

**Comment by aosama** [comment]
Hi Charly,

thanks for the reply, is there any ongoing project that makes a virtual graph model over multiple existing relational databases. if not i wonder if this is a point of interest, thanks for your replies
